version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_parser
    ports:
      - "5432:5432"
    environment:
       POSTGRES_DB: postgres
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: password

    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - pg-network

networks:
  pg-network:

volumes:
  pg_data: